name: Image Scan
description: "Run Image Scan for Trivy"

inputs:
  image_uri:
    required: true
    description: "スキャン対象のイメージURI"
  github_token:
    required: false
    description: "github_token"
  env_prefix:
    required: false
    description: "スキャン対象の環境"

runs:
  using: "composite"
  steps:
    - name: Set Trivy cache dir (workspace local)
      shell: bash
      run: |
        echo "TRIVY_CACHE_DIR=${GITHUB_WORKSPACE}/.cache/trivy" >> "$GITHUB_ENV"

    - name: Cache Trivy
      uses: actions/cache@v4
      with:
        path: ${{ env.TRIVY_CACHE_DIR }}
        key: ${{ runner.os }}-trivy
        restore-keys: |
          ${{ runner.os }}-trivy

    - name: install trivy
      shell: bash
      run: |
        # trivyのインストール
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin latest

    - name: image scan
      shell: bash
      env:
        IMAGE: ${{ inputs.image_uri }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        set -e

        # HTMLテンプレートを作成する
        mkdir -p /tmp/trivy-template
        cat <<EOF > /tmp/trivy-template/html.tpl
        <!DOCTYPE html>
        <html>
          <head>
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        {{- if . }}
            <style>
              * {
                font-family: Arial, Helvetica, sans-serif;
              }
              h1 {
                text-align: center;
              }
              .group-header th {
                font-size: 200%;
              }
              .sub-header th {
                font-size: 150%;
              }
              table, th, td {
                border: 1px solid black;
                border-collapse: collapse;
                white-space: nowrap;
                padding: .3em;
              }
              table {
                margin: 0 auto;
              }
              .severity {
                text-align: center;
                font-weight: bold;
                color: #fafafa;
              }
              .severity-LOW .severity { background-color: #5fbb31; }
              .severity-MEDIUM .severity { background-color: #e9c600; }
              .severity-HIGH .severity { background-color: #ff8800; }
              .severity-CRITICAL .severity { background-color: #e40000; }
              .severity-UNKNOWN .severity { background-color: #747474; }
              .severity-LOW { background-color: #5fbb3160; }
              .severity-MEDIUM { background-color: #e9c60060; }
              .severity-HIGH { background-color: #ff880060; }
              .severity-CRITICAL { background-color: #e4000060; }
              .severity-UNKNOWN { background-color: #74747460; }
              table tr td:first-of-type {
                font-weight: bold;
              }
              .links a,
              .links[data-more-links=on] a {
                display: block;
              }
              .links[data-more-links=off] a:nth-of-type(1n+5) {
                display: none;
              }
              a.toggle-more-links { cursor: pointer; }
            </style>
            <title>{{- escapeXML ( index . 0 ).Target }} - Trivy Report - {{ now }} </title>
            <script>
              window.onload = function() {
                document.querySelectorAll('td.links').forEach(function(linkCell) {
                  var links = [].concat.apply([], linkCell.querySelectorAll('a'));
                  [].sort.apply(links, function(a, b) {
                    return a.href > b.href ? 1 : -1;
                  });
                  links.forEach(function(link, idx) {
                    if (links.length > 3 && 3 === idx) {
                      var toggleLink = document.createElement('a');
                      toggleLink.innerText = "Toggle more links";
                      toggleLink.href = "#toggleMore";
                      toggleLink.setAttribute("class", "toggle-more-links");
                      linkCell.appendChild(toggleLink);
                    }
                    linkCell.appendChild(link);
                  });
                });
                document.querySelectorAll('a.toggle-more-links').forEach(function(toggleLink) {
                  toggleLink.onclick = function() {
                    var expanded = toggleLink.parentElement.getAttribute("data-more-links");
                    toggleLink.parentElement.setAttribute("data-more-links", "on" === expanded ? "off" : "on");
                    return false;
                  };
                });
              };
            </script>
          </head>
          <body>
            <h1>{{- escapeXML ( index . 0 ).Target }} - Trivy Report - {{ now }}</h1>
            <table>
            {{- range . }}
              <tr class="group-header"><th colspan="6">{{ .Type | toString | escapeXML }}</th></tr>
              {{- if (eq (len .Vulnerabilities) 0) }}
              <tr><th colspan="6">No Vulnerabilities found</th></tr>
              {{- else }}
              <tr class="sub-header">
                <th>Package</th>
                <th>Vulnerability ID</th>
                <th>Severity</th>
                <th>Installed Version</th>
                <th>Fixed Version</th>
                <th>Links</th>
              </tr>
                {{- range .Vulnerabilities }}
              <tr class="severity-{{ escapeXML .Vulnerability.Severity }}">
                <td class="pkg-name">{{ escapeXML .PkgName }}</td>
                <td>{{ escapeXML .VulnerabilityID }}</td>
                <td class="severity">{{ escapeXML .Vulnerability.Severity }}</td>
                <td class="pkg-version">{{ escapeXML .InstalledVersion }}</td>
                <td>{{ escapeXML .FixedVersion }}</td>
                <td class="links" data-more-links="off">
                  {{- range .Vulnerability.References }}
                  <a href={{ escapeXML . | printf "%q" }}>{{ escapeXML . }}</a>
                  {{- end }}
                </td>
              </tr>
                {{- end }}
              {{- end }}
              {{- if (eq (len .Misconfigurations ) 0) }}
              <tr><th colspan="6">No Misconfigurations found</th></tr>
              {{- else }}
              <tr class="sub-header">
                <th>Type</th>
                <th>Misconf ID</th>
                <th>Check</th>
                <th>Severity</th>
                <th>Message</th>
              </tr>
                {{- range .Misconfigurations }}
              <tr class="severity-{{ escapeXML .Severity }}">
                <td class="misconf-type">{{ escapeXML .Type }}</td>
                <td>{{ escapeXML .ID }}</td>
                <td class="misconf-check">{{ escapeXML .Title }}</td>
                <td class="severity">{{ escapeXML .Severity }}</td>
                <td class="link" data-more-links="off"  style="white-space:normal;">
                  {{ escapeXML .Message }}
                  <br>
                    <a href={{ escapeXML .PrimaryURL | printf "%q" }}>{{ escapeXML .PrimaryURL }}</a>
                  </br>
                </td>
              </tr>
                {{- end }}
              {{- end }}
            {{- end }}
            </table>
        {{- else }}
          </head>
          <body>
            <h1>Trivy Returned Empty Report</h1>
        {{- end }}
          </body>
        </html>
        EOF

        # HTML出力
        mkdir -p trivy-report

        if ! trivy image --exit-code 0 --format template --template "@/tmp/trivy-template/html.tpl" -o ./trivy-report/index.html ${IMAGE} ; then
          echo "Rerun trivy"
          if ! trivy image --exit-code 0 --format template --template "@/tmp/trivy-template/html.tpl" -o ./trivy-report/index.html ${IMAGE} ; then
            echo "Rerun skip db trivy"
            trivy image --skip-db-update --skip-java-db-update --offline-scan --skip-check-update --exit-code 0 --format template --template "@/tmp/trivy-template/html.tpl" -o ./trivy-report/index.html ${IMAGE}
          fi
        fi

        # イメージスキャン(HIGH, CRITICALが検知された場合もジョブを継続させる)
        trivy image --exit-code 0 --severity MEDIUM --ignore-unfixed --vuln-type os,library ${IMAGE}
        trivy image --exit-code 0 --severity HIGH,CRITICAL --ignore-unfixed --vuln-type os,library ${IMAGE}

    - name: artifact generate
      uses: actions/upload-artifact@v4
      if: always() # ブロックされてもレポート確認
      with:
        name: artifact-image-scan-${{ inputs.env_prefix }}
        path: ./trivy-report/
        retention-days: 1